### ISSUE TITLE
Key sequence to Restart Budgie, preserving all applications and windows 

### ISSUE THREAD

**Issue by apolitech** [UbuntuBudgie/budgie-desktop-environment#10]
If the desktop freez when you are working at something inportant this will be the best thing to do and to have by default .Ctrl+Alt+Esc is the shortcut  and "nohup budgie-panel --replace &" the command. This will be great for a normal user and for a developer(applets, interface etc)

**Comment by fossfreedom** [comment]
no longer convinced on this.  I havent seen any freezes for months now.  Dont regard this as a necessity.
