### ISSUE TITLE
Unexpected Logout After Excessive Tab Switching

### ISSUE THREAD

**Issue by nooballday** [UbuntuBudgie/budgie-desktop-environment#101]
My computer logout itself everytime i am doing excessive tab switching between Apps, but before that strangely my budgie panel closes itself a couple times but restarted again then after few crashes of budgie panel my computer Logout itself

here is what i found in /var/log/syslog

    Jul 23 16:05:39 xfiles kernel: [ 2523.088829] budgie-panel[5717]: segfault at 18bf5 ip 00007f88f3be7189 sp 00007fff34201ca0 error 4 in libgobject-2.0.so.0.5600.1[7f88f3bb1000+52000]
    Jul 23 16:05:39 xfiles gnome-session[5430]: gnome-session-binary[5430]: WARNING: Application 'budgie-panel.desktop' killed by signal 11
    Jul 23 16:05:39 xfiles gnome-session-binary[5430]: WARNING: Application 'budgie-panel.desktop' killed by signal 11
    Jul 23 16:22:17 xfiles appmenu-registr[2911]: g_variant_unref: assertion 'value->ref_count > 0' failed
    Jul 23 16:22:17 xfiles budgie-panel[14647]: BudgieMenuWindow.vala:298: Software has no parent directory, not adding to menu
    Jul 23 16:22:28 xfiles tilix[14675]: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

**Comment by fossfreedom** [comment]
Are you using the global menu applet?

**Comment by nooballday** [comment]
@fossfreedom yes i do

**Comment by fossfreedom** [comment]
ok - this needs to be raised on the upstream applet tracker.  What will be needed is a full debug trace - so you'll need to install the debug symbols for budgie-desktop.

https://github.com/rilian-la-te/vala-panel-appmenu
