### ISSUE TITLE
Closed lid laptop's screen is woken up after suspend

### ISSUE THREAD

**Issue by resolritter** [UbuntuBudgie/budgie-desktop-environment#103]
### Steps to reproduce

1. Have a laptop and an active external monitor into its display ports.
2. Close the laptop's lid. This will make Budgie switch from **Extended display mode (two screens)** to **Single display mode (only your external screen)** automatically.
3. Put your laptop in Suspend through the Start menu.
4. Wake up your laptop again. You'll notice that the (before) inactive laptop display is woken up and displays the Lock Screen.

### Current workaround

After waking up from suspend I have to manually open up the lid and close it, which triggers the environment's switch to **Single display mode**  again.

**Comment by fossfreedom** [comment]
Doubtful this is a budgie matter. This sounds systemd related graphics related or kernel related.

Those sort of issues should be reported to launchpad.net 

    ubuntu-bug linux

**Comment by resolritter** [comment]
My bad, then. I'll look for it and reopen the issue depending on what comes up.
Thank you for the guidance.
