### ISSUE TITLE
18.10 - Function F6 for keyboard backlight does not work

### ISSUE THREAD

**Issue by makitso** [UbuntuBudgie/budgie-desktop-environment#104]
This is an older Dell XPS 15z L511Z.  Nothing happens when pressing the Function key and F6.  For what its worth, Ubuntu 18.04 worked correctly.

**Comment by fossfreedom** [comment]
Not likely to be a budgie matter. Likely to be a kernel regression.

18.10 is likely to use kernel 4.18 which will be uploaded by canonical in the next week or so. Suggest retest again when it is available.  If it still doesn't work then report this to launchpad then

     ubuntu-bug linux
