### ISSUE TITLE
budgie-desktop-common: /etc/profile.d/vte.sh - conflicts with other custom user prompts

### ISSUE THREAD

**Issue by dreamcat4** [UbuntuBudgie/budgie-desktop-environment#105]
Hi there,
Whilst installing budgie desktop on ubuntu 18.04

It seems that the ubuntu package `budgie-desktop-common` installs a file named `vte.sh`.

Then somehow, was added the following line to the end of my `~/.bashrc` file, in my user home folder:

```sh
if [ $TILIX_ID ] || [ $VTE_VERSION ] ; then source /etc/profile.d/vte.sh; fi # Ubuntu Budgie END
```

I also installed TILIX terminal program at the same time. Anyhow this created an conflict with my 3rd party PS1 prompt program (liquidprompt). And Broke my PS1 prompt:

```sh
${debian_chroot:+($debian_chroot)}id@apex:~$ 
```

Not sure why this was needed.

Anyhow, inside the file `vte.sh`, the following lines were commented out, which found to cause this conflict:

```sh
#__vte_prompt_command() {
#  local pwd='~'
#  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
#  printf "\033]0;%s@%s:%s\007%s" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
#}

case "$TERM" in
  xterm*|vte*)
#    [ -n "$BASH_VERSION" ] && PROMPT_COMMAND="__vte_prompt_command" # this bit
    [ -n "$ZSH_VERSION"  ] && precmd_functions+=(__vte_osc7)
    ;;
esac
```

After that my 3rd party prompt program, liquidprompt, started working normally again.

**Comment by dreamcat4** [comment]
Not sure what you want to do about this. There are quite a few different ways to tackle the problem. But I would suggest that (if you really must do this, which I don't believe so, but anyhow), least check if the variable `PROMPT_COMMAND` was already set. Before trying to override it. And if you must override it, then at least you have a capability to print a warning, or do some other type of error handling.

**Comment by fossfreedom** [comment]
Vte.sh is installed by tilix. Our common package simply sources it to ensure tilix works without error

**Comment by dreamcat4** [comment]
After filing this issue I read the wiki page over on Tilix, about VTE breaking stuff.

Here is the a solution for users of liquidprompt, (I have just tested it). This solution assumes that budgie, tilix, and liquidprompt have already been installed first. And the prompt is in a broken state.

First run command in terminal:

```sh
# 1. disable calling vte.sh directly, because it overrides $=PROMPT_COMMAND=
sed -i -e 's~if \[ \$TILIX_ID \] || \[ \$VTE_VERSION \] ; then source /etc/profile.d/vte.sh; fi # Ubuntu Budgie END~# disabled - conflicts with liquidprompt # if [ $TILIX_ID ] || [ $VTE_VERSION ] ; then source /etc/profile.d/vte.sh; fi # Ubuntu Budgie END~g' $HOME/.bashrc
```

Then append lines to the place where liquidprompt is being sourced, either `~.bashrc`, or `~/.profile`)

```sh
# 2. insert these lines to your .bashrc or .profile, directly AFTER sourcing liquidprompt
if [ "${VTE_VERSION:-0}" -ge 3405 ] && [ ! "$_liquidprompt_vte_enabled" ] && [ "$PROMPT_COMMAND" = "_lp_set_prompt" ]; then

  # but sourcing this vte.sh file, it overwrites our prompt
  . /etc/profile.d/vte.sh

  _lp_set_prompt_vte()
  {
    _lp_set_prompt
    VTE_PWD_THING="\[$(__vte_osc7)\]"
    PS1="$PS1$VTE_PWD_THING"
  }

  # set it back, but appen vte afterwards
  PROMPT_COMMAND="_lp_set_prompt_vte"

  # tell vte.sh that the prompt has already been set, to include vte
  export _vte_prompt_enabled=true
  export _liquidprompt_vte_enabled=true
fi
```

**Comment by fossfreedom** [comment]
if you do a pull-request then I can look to merge this.

Such a PR needs to cater for non-liquidprompt users, liquidprompt users on first logon and resolving issues where liquidprompt is installed after logon.

**Comment by dreamcat4** [comment]
It's understood now, that this issue is being caused by Tilix (the vte.sh file is doing this, not your lines added into bashrc file, which calls the vte.sh). I just wanted to include the solution here for now, for completeness. In case anybody else searches it. (Anyhow, we should moving this issue over to tilix repo, right?)

**Comment by fossfreedom** [comment]
hmm - I'm guessing the tilix maintainer will simply say that "that is the way it works".  I think this should be handled at a distro level since tilix cannot/probably shouldnt need to worry about every new variation that is outside his control.

**Comment by dreamcat4** [comment]
Yeah man. I just checked past Tilix issues tracker. And there are lots of 'vte is broken' issues, all closed by the maintainer. According to the wiki page, the expects people to each individually fix the PS1 prompt / PROMPTCOMMAND. On a case by case basis.

But I think you might be right in thinking that this can be done dynamically, by improving the file vte.sh. If he is going to accept that suggestion / improvement (or not) - IDK !
