### ISSUE TITLE
"Launch Terminal" shortcut opens a terminal but in the wrong working directory - target 18.04

### ISSUE THREAD

**Issue by jonathansty** [UbuntuBudgie/budgie-desktop-environment#107]
**Operating System**: e.g. Pop!_OS 18.04 LTS
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**
When pressing "CTRL+ALT+T" to open a default terminal it opens a terminal with "/usr/share/budgie-desktop/keycontrol" as current working directory. Expected here would be to have a terminal open in $HOME

Might be worth mentioning that by default Pop!_OS did not come with Budgie Desktop and I installed it using ```apt```
 
**Steps to reproduce the issue**
1. Log into Budgie desktop
2. Press CTRL+ALT+T 
3. Observe a terminal startup with a wrong working directory.

**Comment by fossfreedom** [comment]
logout and login - should only happen on the very first logon.

**Comment by jonathansty** [comment]
Ah yes seems so, why is that the case?

**Comment by fossfreedom** [comment]
on first logon a script is run that sets up various stuff - it cd's to to the keycontrol folder ... but forgets to cd back to home after completing that initial bit of key setup stuff

https://github.com/UbuntuBudgie/budgie-desktop-environment/blob/master/etc/profile.d/10-budgie-desktop.sh

**Comment by fossfreedom** [comment]
lets leave the issue open - its a good reminder to fix this - 10 second fix  - half an hour testing!

**Comment by jonathansty** [comment]
Ah sure, I thought that this issue might already have been on your radar for some reason :)

**Comment by fossfreedom** [comment]
fixed in 18.10 - will backport to 18.04.  Keeping this open until its done in 18.04

**Comment by fossfreedom** [comment]
Demote this to Inbox - only backport to 18.04 if there are any other issues that need to  be resolved in the BDE package

**Comment by fossfreedom** [comment]
Ok - not really worth the effort too backport to 18.04 - its a one off issue. Closing since it is fixed in later versions.
