### ISSUE TITLE
Incorrect window buttons placement 

### ISSUE THREAD

**Issue by Jacob-Vlijm** [UbuntuBudgie/budgie-desktop-environment#108]
On a fresh install of UB 18.10, window button placement (left/right) does not match settings on all windows, When set to "left", at least synaptic and firefox' buttons are still on the right, even after a restart.

**Comment by fossfreedom** [comment]
Found out that Iain's budgie-desktop mutter 3.30 patch does not set the key org.gnome.desktop.wm.preferences button-layout

If you fiddle with that then the stubborn windows also change.  

Need to figure out why Iain's patch isnt changing the button-layout key.

**Comment by fossfreedom** [comment]
fixed by this commit https://github.com/UbuntuBudgie/budgie-desktop/commit/b2d7a8b519d3c5293cecdb21360c3a2cbe47162e

**Comment by Jacob-Vlijm** [comment]
Brilliant! I actually assumed the key was set, because some windows did respond correctly on settings change.

**Comment by fossfreedom** [comment]
There are actually two keys that set the decoration position. Different apps respond to each key
