### ISSUE TITLE
PrintScreen key

### ISSUE THREAD

**Issue by apolitech** [UbuntuBudgie/budgie-desktop-environment#11]
Thanks to David Mohammed we have a fix for it that we need to implemant it! Settings-> Keyboard-> Shortcuts-> Custome Shortcut-> + -> Name: Screenshot -> Command: gnome-screenshot ->Add  and then add the print screen key to the schortcut

**Comment by GeneralAccess** [comment]
I can do all of this except pressing the key on the panel which is headed "Enter the new shortcut" - nothing happens, other keys will work though.

**Comment by fossfreedom** [comment]
@ChrisOfBristol you need to find the screenshot keybinding in the list - press del to delete it before your custom keybind with printscrn will work

**Comment by fossfreedom** [comment]
from Bernard Gray - community room

This is the initial script, verbatim:
https://paste.ubuntu.com/26412947/
dconf to disable keybindings: https://paste.ubuntu.com/26412949/
dconf with our keybindings: https://paste.ubuntu.com/26412953/
key things to note, the script uses uuidgen to generate custom names for the keys, then applies them to the files via envsubst
I also have full control over all clients in my environment, so I haven't spent any time making this more generic - however, I have some thoughts :grinning:
Bernard Gray
@cleary
21:40
create a dconf file per custom key, and set a standard directory location to hold them
the file only needs to contain the [custom-keybindings/$UUID] heading, and the binding/command/name variables
parse the files in that dir, auto-generate the [/] custom-keybindings=['/org/gnome/settings.../'] array
possibly do a check to see if there's any existing keys that are going to block the custom key
^ this will let you guys have an easy interface to add keys, and allow users (like myself :wink: ) some easy customisation options

**Comment by oguz-ismail** [comment]
> @ChrisOfBristol you need to find the screenshot keybinding in the list - press del to delete it before your custom keybind with printscrn will work

Except it doesn't work you fucking retard. PrtSc still takes a screenshot of the screen
