### ISSUE TITLE
Lock Screen Activation - cant escape blank

### ISSUE THREAD

**Issue by RaeldZues** [UbuntuBudgie/budgie-desktop-environment#112]
Upon activation of the lock screen, I am provided a blank screen, despite providing a photo to the settings, background  lock screen feature. The screen is black, unable to escape it and forced to reboot. This is not just the ubuntu version but the solus version of the budgie desktop

**Comment by fossfreedom** [comment]
Highly likely to be a graphics issue. 

General support is via our discourse forum

https://discourse.ubuntubudgie.org

In this case probably best to file a bug on launchpad against linux(ubuntu) and the triagers can help further.

You will need to detail what your graphics card and the driver you are using.

**Comment by RaeldZues** [comment]
Thank you. This pushed me in the right direction to getting it fixed. I appreciate your help. @fossfreedom
