### ISSUE TITLE
ClockWorks applet's icon shows incorrectly on the panel

### ISSUE THREAD

**Issue by Jacob-Vlijm** [UbuntuBudgie/budgie-desktop-environment#113]
Since 18.10, the icon shows as a big dot. Not sure if this is a theme issue.

![image](https://user-images.githubusercontent.com/8932980/47520464-8864d580-d890-11e8-801e-5328fc2ccc36.png)

**Comment by fossfreedom** [comment]
Kind of blocked by https://github.com/UbuntuBudgie/budgie-extras/issues/106

Clockworks is going to be removed in 19.04 / Debian due to python3-svgwrite being removed from the repos.

**Comment by Jacob-Vlijm** [comment]
Fixed it by (re-) creating icon.
