### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by apolitech** [UbuntuBudgie/budgie-desktop-environment#12]
![untitled](https://cloud.githubusercontent.com/assets/14872517/15466611/2b25bafe-20e3-11e6-8fb4-94f3dcd835e5.png)
"sudo apt purge libnotify-bin" will fix the problem!

Update!!!!
There are some apps that will install by default the  libnotify-bin so that is not realy a fix!!!

**Comment by fossfreedom** [comment]
https://github.com/solus-project/budgie-desktop/issues/451

**Comment by fossfreedom** [comment]
removed notify-osd in 16.04 branch - release 0.3.3
