### ISSUE TITLE
Package budgie-weather-applet

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#124]
Consider replacing the now obsolete budgie-weather-applet with this new project https://github.com/Dirli/budgie-weather-applet

Need to evaluate the project and stability of the applet.

**Comment by fossfreedom** [comment]
Same QA checks as the budgie-sys-monitor-applet required.   Feedback to be made upstream to Dirli's github repository.

**Comment by fagunbhavsar** [comment]
Two things:

1. It does not fetch the correct current location details, hence it shows incorrect sunrise and sunset time
![Screenshot 2018-12-15 at 12.00.02 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be92c66b56aab0014a28bec/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7851e32a64c5b27af1122b4f5f5d5edd3c4a4356bcbbd671f3e57862804e0ebf84655776c23e12aab18349b901bb71d94f8db6e9d94ed2f42f67b6d5db1063474f4dcbed5727a29941c95df24fe94c53a7153062ee752431.png)

2. Not able to change the location or able to select multiple locations

**Comment by fossfreedom** [comment]
1. Please create an issue upstream
2. Re. Multiple locations. Interesting idea. That should be a request for upstream asking if that enhancement is something they are interested to implement

I don't understand your location issue. Maybe it doesn't recognise your immediate town. Try another  bigger town or city close to you

**Comment by fagunbhavsar** [comment]
@fossfreedom Hey, earlier I was not able to search and select different location (may be, I have overlooked the configuration from desktop settings). As of now, the issue I am facing is - although I am able to search and select different location - the selection is not dynamic, after selecting a new location, I need to restart my system in order to take place the changes

**Comment by fossfreedom** [comment]
@fagunbhavsar hmm - that doesn't sound good.  Well found.

Please raise a separate issue upstream on Dirli's github tracker.
