### ISSUE TITLE
Package budgie-sys-monitor-applet

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#125]
Consider packaging this project https://github.com/Dirli/budgie-sys-monitor-applet

**Comment by fossfreedom** [comment]
Bionic and Cosmic test builds are available to test

https://launchpad.net/~ubuntubudgie-dev/+archive/ubuntu/unstable-test

package is "budgie-sys-monitor-applet"

QA Checks - stability?  Does it crash the panel after running for a period of time.

Ease of use?

All issues should be raised on Dirli's upstream tracker (link in first comment)

**Comment by fagunbhavsar** [comment]
Couple of issues:

1. It is possible to remove all sensors and save the applet - after removing all sensors, upon saving the applet, it shows "No Output"message. [Please see the screenshot] 

![Screenshot 2018-12-15 at 12.15.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be92c66b56aab0014a28bec/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7851e32a64c5b27af1132e4f5f5e5edd3c4a4356bcbbd671f3e57862804e0ebf84655776c23e12aab18349b901bb71d94f8db6e9d94ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe94c50ad113364e6762431.png)

2. Upon selecting {cputemp} and adding to existing list of sensors, if trying to save - it shows an error "/sys/class/hwmon/ is empty" [Please see the screenshot]
![Screenshot 2018-12-14 at 11.56.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be92c66b56aab0014a28bec/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7850e32a64c5b279f1172d4f5e585ecc3c4a4356bcbbd671f3e57862804e0ebf84655776c23e12aab18349b901bb71d94f8db6e9d94ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe94c53a413306be7772431.png)

3. Not able to add censor {cpu\d*} CPU and {bat\d*} Battery - as they are not supported with regexp \d*, without it they are working correctly. Is this a correct behaviour?
