### ISSUE TITLE
Package applet cpufreq

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#129]
When its ready - look to package this project https://github.com/Dirli/budgie-cpufreq-applet

**Comment by fossfreedom** [comment]
v1.0.1 published upstream

packaged as budgie-cpufreq-applet 

test PPA: ubuntubudgie-dev/unstable-test

README instructions upstream says works on sandybridge or later processors.

No idea what happens if installed on earlier processors / virtualbox - I guess somesort of error message should be somehow displayed since the applet can only be installed on real hardware.

**Comment by fagunbhavsar** [comment]
Right now, using VB, I am unable to find this applet under budgie applet list

**Comment by fossfreedom** [comment]
Have you installed budgie-cpufreq-applet then logged out and logged in?

You should see an applet "Cpu Frequency" available to be added to your panel.  I certainly see that on my real machine - I haven't tested in virtualbox though.
