### ISSUE TITLE
Apply PR to resolve pixelsaver background and relief issues

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#135]
Apply alunux PR to resolve the above.

**Comment by fossfreedom** [comment]
Backported to bionic and cosmic

**Comment by fagunbhavsar** [comment]
How to test this? @fossfreedom

**Comment by fossfreedom** [comment]
Try a few themes.

For applications that DO NOT have client side decorations e.g. libreoffice, maximise the window and look at the minimise/maximise & close buttons in the panel - do they look OK?

On Thu, 3 Jan 2019 at 11:25, fagun <notifications@github.com<mailto:notifications@github.com>> wrote:

How to test this? @fossfreedom<https://github.com/fossfreedom>
