### ISSUE TITLE
Launcher fails on Nemo 4.0.6

### ISSUE THREAD

**Issue by makitso** [UbuntuBudgie/budgie-desktop-environment#151]
Base is UB 19.04, with gnome-terminal installed.  Launcher below works correctly i.e. terminal window opens and requests sudo password.

Installed ppa:ubuntubudgie/backports and then nemo 4.06
Rebooted
Launcher no longer works -- no window opens, nothing.

[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Icon[en_US]=gnome-panel-launcher
Name[en_US]=Run Trim
Exec=sudo sh -c "fstrim -v /; fstrim -v /home; sleep 5"
Name=RunTrim
Icon=/home/rob/user1/Graphics/block-device.svg

**Comment by makitso** [comment]
Ok, got my launcher to work -- but some changes were needed for nemo 4.

Old
Terminal=true
Exec=sudo sh -c "fstrim -v /; fstrim -v /home; sleep 5"

New
Terminal=false
Exec=gnome-terminal -- bash -c "sudo fstrim, -v/; sudo fstrim -v /home; sleep 5"

**Comment by fossfreedom** [comment]
noted.  and thanks.
