### ISSUE TITLE
Show the UB logo in Details screen

### ISSUE THREAD

**Issue by uD4ra** [UbuntuBudgie/budgie-desktop-environment#17]
We need help to add a **small C based patch** to the **Details** screen in **GNOME Settings**. It'll make it possible to **show the budgie-remix logo in system Details screen**. At the moment, it is hard-coded with the Ubuntu GNOME logo.

![budgie-remix_system](https://cloud.githubusercontent.com/assets/12265797/15984585/c47b2f68-2fd9-11e6-9670-f6aa93e3f918.jpg)

**Comment by crutchcorn** [comment]
More info from @HEXcube here:

Patches by Ubuntu GNOME:
- [56_use_ubuntu_info_branding.patch](https://bazaar.launchpad.net/~ubuntu-desktop/gnome-control-center/ubuntu/view/head:/debian/patches/56_use_ubuntu_info_branding.patch)
- [ubuntu-gnome-version.patch](https://bazaar.launchpad.net/~ubuntu-desktop/gnome-control-center/ubuntu/view/head:/debian/patches/ubuntu-gnome-version.patch)

I will be trying to work on a fix. Might drop two; a temporary one for now and one that I will submit upstream to GNOME

**Comment by RohanVilloth** [comment]
**Solus** uses [this patch](https://git.solus-project.com/packages/gnome-control-center/tree/files/0001-Add-Solus-Branding.patch?id=e5e813ddf1a8fec0c1695e9a9800890fe570ee10) to display _Solus logo_. They previously used [another patch](https://git.solus-project.com/packages/gnome-control-center/tree/files/0001-Add-Budgie-Branding.patch?id=457435f) to display _Budgie logo_.

**Comment by InitRoot** [comment]
I will take care of this.
Forked gnome-control-centre and will apply then update with .patch file.

**Comment by fossfreedom** [comment]
@FransHBotes that would be wonderful if you can do this - we can patch 16.04 and 16.10 like this.

For 17.04 though we will need to work with Ubuntu GNOME (they are the maintainers of gnome-control-centre for ubuntu) - we would need a generic method where both distros can "override" the base logo rather than hard-coding this via a C patch.

**Comment by fossfreedom** [comment]
"I think ideally you would have a separate package that includes your icon and distro name changes. That package would use dpkg-divert in its scripts (pretinst maybe?) and clean up after itself (postrm?) when it's removed." - Jeremy Bicha

Intriguing...

from pinguy builder

    cp -a /etc/PinguyBuilder/icons /usr/share/
    rm -rf /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png
    ln -s /usr/share/icons/ubuntu-logo-icon.png /usr/share/icons/hicolor/256x256/apps
    chmod 777 /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png
    chmod 777 /usr/share/icons/ubuntu-logo-icon.png
    gtk-update-icon-cache
    update-icon-caches /usr/share/icons/*

**Comment by fossfreedom** [comment]
branding-ubuntu package has an example of how to use dpkg-divert

**Comment by fossfreedom** [comment]
fix required in both Pocillo  Icons and budgie-desktop-common package
Pocillo icons needed a symbolic link "ubuntu-logo-icon.svg" pointing to our distributor logo in the 64/apps folder

budgie-desktop-common needed preinst and postrm dpkg-divert rules repointing /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png to our version that is installed in the package

**Comment by fossfreedom** [comment]
this can now be tested by adding the PPA ubuntubudgie-dev/unstable-test on 19.04(disco), updating.

An update to budgie-artwork containing a revised Pocillo will be made available in the unstable-test PPA shortly

**Comment by fossfreedom** [comment]
now in 19.04 ISO 22 Jan 19
