### ISSUE TITLE
Update SVG names

### ISSUE THREAD

**Issue by codic12** [UbuntuBudgie/budgie-desktop-environment#174]
They are called budgie-remix Logo, they should be Ubuntu Budgie Logo. Am willing to make a PR for this later-just need to change one key in the XML

**Comment by fossfreedom** [comment]
Sure ... PR would be welcome

**Comment by codic12** [comment]
Will do

**Comment by codic12** [comment]
https://github.com/UbuntuBudgie/budgie-desktop-environment/pull/175
and
https://github.com/UbuntuBudgie/budgie-desktop-environment/pull/176
