### ISSUE TITLE
Sidebar is white when using Qogir

### ISSUE THREAD

**Issue by GrindamN** [UbuntuBudgie/budgie-desktop-environment#177]
Go to the Settings, Select the Applications option. The sidebar is now white, and you can't see the text next on the right of respective app icon. The bug only happens if you use Qogir Budgie and Qogir Budgie Light theme. Guess we should ping Vince. 
![bug](https://user-images.githubusercontent.com/9149076/74105302-dcb2c800-4b5c-11ea-9bba-b872c8c3e54a.jpeg)

**Comment by fossfreedom** [comment]
Test with the latest upstream Qogir theme. If it's the same then drop an
issue there. If it's fixed we need to package the latest version

**Comment by GrindamN** [comment]
No issue with the latest upstream. Seems fixed.

**Comment by fossfreedom** [comment]
Fixed in v0.12.0 of ubuntu-budgie-themes
