### ISSUE TITLE
Weird accent keyboard

### ISSUE THREAD

**Issue by costales** [UbuntuBudgie/budgie-desktop-environment#186]
Hi,

I'm writing with accents (Spanish & Asturian languages) and there is a weird feeling in Ubuntu Budgie 20.04. When I press the key ' and after that the vocal, I see an accent with a space. Please see this animation as reference:

![issue](https://user-images.githubusercontent.com/5886786/80758831-8e4b0f00-8b36-11ea-8ecc-4a37e4495baa.gif)

It's the 1st time I see that behavior in a OS and honestly I hate it. Please, how could I disable it? Could it be a bug?

Thanks in advance and a hug!

PS: In any previous LTS or OS, you click ` and you don't see anything, then you click the vocal and the accent appears.

**Comment by fossfreedom** [comment]
Budgie doesnt manage anything in this area. So it is most likely a GNOME issue of some sort. Double check in a UB live session to see if you can reproduce the issue.

I would assume you will see the same thing.

If it the same, then also test a live session of Ubuntu.

**Comment by costales** [comment]
Thanks a lot @fossfreedom 
I think is a GNOME issue too, I reported [it here](https://gitlab.gnome.org/GNOME/gnome-desktop/-/issues/153).
A hug!

**Comment by costales** [comment]
Hi,

I fixed it.

I set to none the Keyboard input method:

![Screenshot from 2020-05-01 13-32-10](https://user-images.githubusercontent.com/5886786/80803200-e07d4600-8bb1-11ea-90a7-f30807d57375.png)

And after reboot, I remove these packages:

`sudo apt purge ibus-gtk3 ibus-gtk gir1.2-ibus-1.0 ibus ibus-data`

Best regards and thanks :)
