### ISSUE TITLE
Nemo file searching

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#192]
Nemo v5 includes improved file-searching.

Need to keep an eye on how it does this - if its via tracker or some-other mechanism.

If its good enough we can drop catfish and our right-click catfish search option.

**Comment by Coeur-Noir** [comment]
https://github.com/linuxmint/nemo/commit/3541baa5502e896ebea0d7892569cf4691a7093e

I'd say other mechanism - search helper

https://github.com/linuxmint/nemo/commit/3ebecad1e9a1eb5784245334489bb92fc913e055
