### ISSUE TITLE
Doubles

### ISSUE THREAD

**Issue by Quasicitizen** [UbuntuBudgie/budgie-desktop-environment#199]
Switched from Gnome and seeing these 'anomalies'? 
Double files, each opening differently looking windows with Home files
and those three different font apps - is this normal?
![bug](https://user-images.githubusercontent.com/69772408/213774529-237ec66c-ea75-46c0-8318-d2b5e6890f7f.png)

**Comment by fossfreedom** [comment]
So you probably have both nautilus and nemo installer... both call themselves Files

Fonts is probably the gnome Fonts app.

That's the issue  with coming from another flavour base ... we don't ship the same apps and apps often refer to themselves in a similar manner
