### ISSUE TITLE
Default apps to be replaced, removed or added

### ISSUE THREAD

**Issue by spottech** [UbuntuBudgie/budgie-desktop-environment#2]
| Software | Replacement | Comment |
| --- | --- | --- |
| Contacts app | gnome-contacts | maybe evolution, but then replace gnome-calendar and geary mail too - SpotTech |
| Mail client | geary | maybe evolution, but then replace gnome-calendar and gnome-contacts too - SpotTech |
| gthumb | gnome-photos | Unless with gnome-photos - SpotTech |
| gnome-games-meta |  | ok but not in dep of environment maybe meta package budgie-remix-extras - SpotTech |
| transmission |  | ok but not in dep of environment maybe meta package budgie-remix-extras - SpotTech |

Best integration with GNOME and Budgie:

| Meta-package | Dependencies | Comment |
| --- | --- | --- |
| budgie-remix-base |  | all meta-packages build with seeds files https://github.com/budgie-remix/os-patches/tree/master/budgie-remix-meta |
| budgie-remix-desktop |  | all meta-packages build with seeds files https://github.com/budgie-remix/os-patches/tree/master/budgie-remix-meta |
| budgie-remix-extra |  | all meta-packages build with seeds files https://github.com/budgie-remix/os-patches/tree/master/budgie-remix-meta |

**Comment by spottech** [comment]
Ok for the wishlist, 
but if I want remove one of this package by apt autoremove --purge, I purge budgie-desktop too

**Comment by Foggalong** [comment]
As far as I know, Shotwell is [no longer maintained](https://en.wikipedia.org/wiki/Shotwell_%28software%29).

**Comment by spottech** [comment]
no longer maintained but it's an good software :)

**Comment by Foggalong** [comment]
Yeah, but switching over to unmaintained software from maintained software is generally a bad idea. If something serious breaks in the middle of a release cycle then it'll never be fixed.

**Comment by RohanVilloth** [comment]
**GNOME Calendar** with **Evolution**, **GNOME Photos** with **Shotwell**? :open_mouth: No way! The bundled apps should be the ones that integrates better with the underlying GNOME stack. _Calendar_, _Software_, _Photos_ and _Transmission_ sure aren't the best apps in their field. But they are currently the best ones suited to bundle on a GNOME based distro.

Say we replace _Transmission_ with _Deluge_ or _Vuze_, _Calendar_ with _Evolution_, _Software_ with _Deepin Store_ and so on, the final result'd be a "frankenstein" desktop that don't feel like it's part of a single system. :scream: User experience'd be terribly broken.

However, **gThumb**'s planned to be dropped in favor of **GNOME Photos**, coz _Photos_ from GNOME 3.20 has many improvements. :relaxed: And all those games are from `gnome-games` metapackage. I'd be happy to see them gone, but I think GNOME has a dependency on it. :confused:

**Comment by spottech** [comment]
issue updated, please edit first post and add your ideas in comment section

**Comment by RohanVilloth** [comment]
I removed GNOME Software from the table:

| Software | Replacement | Comment |
| --- | --- | --- |
| gnome-software | nothing | ok for gnome-software, but it buggy for install local deb, best solution is gdebi + synaptic - SpotTech |

GNOME Software can't be dropped just coz it can't sideload debs. :confused: Debian packages were always meant to be installed from repos. Sideloading debs is not a good practice, but some app vendors make their debs available as standalone installers. They should be moving to _Snappy_ packages soon. Anyway, Ubuntu is currently [patching GNOME Software to enable installing snaps and local debs](http://www.omgubuntu.co.uk/2016/04/ubuntu-16-04-deb-software-install-error), so it's just a temporary issue. :relieved:

About adding _Geary_ as the mail client, like _Shotwell_ and _California_ it became unmaintained too when [Yorba](https://en.wikipedia.org/wiki/Yorba_Foundation#Main_developments) shut down last year. However, it's still maintained by the community but [activity seems to have decreased a lot according to OpenHub statistics](https://www.openhub.net/p/geary). elementary OS forked _Pantheon Mail_ from it, but using it may pull in dependencies from _Pantheon_. :worried:

**Comment by Foggalong** [comment]
I thought Software _could_ handle Debian packages (and Snappy too!) or at least it could last I used it. As far as I know it's just a bug in 16.04 which means it can't at the moment.

Pantheon isn't really viable because as part of their streamlining they've removed a lot of baggage that eOS doesn't need, but that baggage includes the integration with other DEs.

**Comment by RohanVilloth** [comment]
@Foggalong The deb install bug is just a temporary issue. An update enabling local deb install has already [arrived in proposed repo](https://launchpad.net/ubuntu/+source/gnome-software/3.20.1+git20160426.1.a976144-ubuntu-xenial-0ubuntu1)! :smiley: Another important feature added by this update is [support for snap packages](http://www.omgubuntu.co.uk/2016/04/can-now-install-snappy-apps-software-center)! :heart_eyes: No other "Software Store" has support for these next generation packages (**snaps** and **flatpaks**) yet. So, currently **GNOME Software** is the best choice for an Ubuntu based distro.

**Comment by fossfreedom** [comment]
ok - summary - community chose geary as the mail client.  Raise separate issue for 17.04 software defaults
