### ISSUE TITLE
Software Updater: Says there are updates, but does not list any

### ISSUE THREAD

**Issue by DennisFaucher** [UbuntuBudgie/budgie-desktop-environment#203]
Seems to be in a loop
![Software Update](https://github.com/user-attachments/assets/ec947dea-78bd-49f2-bf56-d5096379b0c4)
![Snapshot_2024-07-27_11-10-33](https://github.com/user-attachments/assets/03cbac8f-291c-42fb-ae04-6c84d6e97960)

**Comment by fossfreedom** [comment]
Ah. Well nobody claims software updater is correct all the time!

Check in a terminal if there are updates and  what their status is

    sudo apt update 
    sudo apt full-upgrade

**Comment by DennisFaucher** [comment]
🙂

**Comment by DennisFaucher** [comment]
Might have been related to file-roller being held back as a phased update in 24.04. I forced an install of file-roller and now Software Updater is happy.
