### ISSUE TITLE
Include tlp in default installation

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-desktop-environment#25]
[TLP](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html) is a power management tool for GNU/Linux distributions. The purpose of TLP is to offer optimized battery life.

It would be better if TLP can be included in default installation of **budgie-remix**.

**Off topic**
Solus is [planning](https://solus-project.com/2016/08/07/this-week-in-solus-install-33/) to include tlp in upcoming releases.

> We are also happy to announce that TLP will be available in future shipped ISOs and enabled out-of-the-box. For those unaware, TLP is a power management tool that aims to optimize battery life on laptops when they’re unplugged. This can range from power management for PCI-e devices to USB autosuspend, and more. By us enabling TLP out-of-the-box by default, you can expect to see improved battery life!

**Comment by fossfreedom** [comment]
It already is a default recommendation. Look at the Debian control file for the default apps such as tlp
