### ISSUE TITLE
Control panel entries are not available in menu

### ISSUE THREAD

**Issue by niyasc** [UbuntuBudgie/budgie-desktop-environment#26]
Control panel entries such as _Background_, _Language Support_, _Notifications_, _Online Accounts_ ..etc are not available in applications menu.

All these options are available in Solus application menu and these entries are available to search.

**Comment by fossfreedom** [comment]
Suggest check yakkety. Maybe a gtk 3.20 feature that you are seeing.

**Comment by niyasc** [comment]
Yeah. I will just confirm that. But, If I remember correctly, I have seen this in fresh installation of Solus 1.2 also, which uses Gtk 3.18.x.

**Comment by fossfreedom** [comment]
Probably need to look at the solus gnome control center source. Likely to have patched the source for gnome  control center

**Comment by niyasc** [comment]
Seems this patch is making difference. It is present in `gnome-control-center` package hosted on [Solus server](https://git.solus-project.com/packages/gnome-control-center/log/).

[0001-panels-Do-not-hide-items-from-menu-listings-i.e.-Bud.txt](https://github.com/budgie-remix/budgie-desktop-environment/files/431740/0001-panels-Do-not-hide-items-from-menu-listings-i.e.-Bud.txt)

**Comment by fossfreedom** [comment]
Hmm that patch seems to be editing the .desktop files to remove nodisplay=TRUE.  What if you do something similar but just copy the .desktop file from /usr/share/applications to .local/share/applications

**Comment by niyasc** [comment]
Sorry for delayed response. Remembered this issue, when I saw some queries in community page. I tried removing `nodisplay=true` entry from `.desktop` file. But that did n't make any difference. :cry:

**Comment by fossfreedom** [comment]
:(. Just to check... You logged off and back on again to allow the new changes to be reloaded?

**Comment by niyasc** [comment]
First I tried restarting panel, then tried log off, but no result.

**Comment by fossfreedom** [comment]
very odd - if you make the nodisplay change, logoff/login ALT+F2 and search it finds the new entry - not shown in the menu though.

**Comment by niyasc** [comment]
Yeah. I was able to confirm it. Just created a temporary desktop entry without `nodisplay` option and was able to see in `ALT + F2` search box, but not in application menu.

Also, explored Solus `.desktop` entry and was not able to observe any difference other than translated text and absence of `nodisplay` option.
