### ISSUE TITLE
Change icon theme

### ISSUE THREAD

**Issue by spottech** [UbuntuBudgie/budgie-desktop-environment#3]
Move icons set Moka to [Papirus](https://github.com/buiminhtien12345/papirus-icon-theme). I can push source of my modded icons set

![capture du 2016-04-20 17-22-04](https://cloud.githubusercontent.com/assets/13060777/14680139/75580b8a-071c-11e6-970d-14d37c71524f.png)

**Comment by HEXcube** [comment]
@spottech  U mean drop Moka icon theme and move to Paper icon theme? :confused:

**Comment by spottech** [comment]
Not paper, papirus-gtk
It's mine and it's great lol
![capture du 2016-04-20 17-22-04](https://cloud.githubusercontent.com/assets/13060777/14680139/75580b8a-071c-11e6-970d-14d37c71524f.png)

**Comment by HEXcube** [comment]
This one: http://www.noobslab.com/2015/10/papirus-icons-for-unity-papirus-theme.html and https://github.com/varlesh/papirus-suite ? 0:confused: I confused it with [Papyros](https://papyros.io) at first, lol! :laughing:

**Comment by spottech** [comment]
Yes this, it's great :D

**Comment by RohanVilloth** [comment]
For this cycle (16.04.x) we're staying on **Moka** icons and **Arc** GTK theme to follow the style of Solus 1.x. However, we were already discussing changing the icon theme for next release cycle:
- **Numix Circle** is a strong candidate. With the core Numix dev @Foggalong in our team, we have an added advantage
- **Paper** icon theme from Sam Hewitt (@snwh), the creator of Moka. @udara-u3 suggested _Paper_ along with Adapta GTK theme for a complete Material Design style. But, I'm not really sure if we should adapt a fully Material style (though I like it a lot! :smile: )
- Other Material Design inspired icons (including **Papirus**). There's also **Frosting** icon theme by @crutchcorn. It's a continuation of Solus's original icon theme - _Evopop_.

**Comment by crutchcorn** [comment]
HOW DARE YOU???? (jk)
I would recommend not using Frosting at this time. Life has caught up with me and disallowed me time to work on it. Until my other teammates (@danielhickman and others), I can't see it getting too much more love soon (though I would love to come back to it when things slow in a few months)

**Comment by RohanVilloth** [comment]
@crutchcorn Glad to have you in the discussion. :relaxed: So **Frosting** isn't actively maintained at the moment, right? @fossfreedom is looking for a long term maintained icon and theme with good support for Budgie desktop. **Numix** seems to be most practical option at the moment. But now that Sam has resumed development of **Paper**, we're also considering that option. Either way, we're looking for a theme that's maintained for atleast the next LTS cycle.

**Comment by Foggalong** [comment]
I've moved all the talk of GTK themes to issue #6 because that's a different topic. On the icon side of things, something to remember is that all these themes have different levels of coverage, especially for application icons. I've drawn up a little table of all the ones brought up in this chat plus a few other common ones.

| Theme | Apps Covered |
| --- | --- |
| Numix | 3727 |
| Moka | 1311 |
| Pinbadge | 598 |
| Paper | 594 |
| elementary+ | 231 |
| Frosting | 229 |
| MaterialOS | 213 |
| Papirus | 178 |
| Lüv (previously Flattr) | 43 |
| Arc | 31 |

Obviously coverage isn't everything, but there's a very wide disparity in some of the themes being brought up. As new themes are brought up I'll just add them to this list (which you can link to from [here](https://github.com/budgie-remix/budgie-desktop-environment/issues/3#issuecomment-213750728)) rather than making more comments.

**Comment by crutchcorn** [comment]
Yeah, I can't see Frosting taking a maintainer anytime soon either. Especially because I haven't explicitly written down the new icon guidelines yet. 

Also, I'd like to claim BS from @foggalong; Pinbadge is NOT a "common one". ;P

**Comment by RohanVilloth** [comment]
I didn't know **Pinbadge** had that many icons! It's got an [Android icon pack](https://github.com/Pinbadge/pinbadge-android-theme/) and a [G+ community](https://plus.google.com/communities/112507470833527559949) too. @crutchcorn and @ploctaux I see u guys are [on the team](https://github.com/orgs/Pinbadge/people) . Even more reason to give it a try! :relaxed:

**Comment by snwh** [comment]
@Foggalong where are you coming up with those numbers?

also, @spottech what have you done to my Paper icons?! :P

**Comment by snwh** [comment]
also, @spottech what have you done to my Paper icons?! :P

**Comment by spottech** [comment]
@snwh nothing for now , I am left to zero . I work on papirus yet 😊

**Comment by RohanVilloth** [comment]
@snwh  Aah, so Papirus is derived from _Paper_ icon theme. :smile: Had a look at [Papirus' GitHub repo](https://github.com/buiminhtien12345/papirus-icon-theme) It says:

> Modded and adaptive [Paper icon theme](https://github.com/snwh/paper-icon-theme) for KDE distros.

It has a [full theme suite](https://github.com/varlesh/papirus-suite) too.

**Comment by Foggalong** [comment]
@snwh it's the number of icons in the apps direction of whatever size was most common. The command to do this was: `cd /usr/share/icons/Some-Theme/48/apps && ls -1 | wc -l`. As mentioned in the original comment it's not a good indicator of whether the icon theme is good, but worth taking note of before picking something like Papirus over something like Paper.

**Comment by deadbaed** [comment]
how many apps materialos have?

**Comment by RohanVilloth** [comment]
How could I forget [MaterialOS](http://materialos.com/)! I've got the Android icon pack and CM12 theme installed on my Cyanogen fone. :smiley: @ploctaux I see that you're on [MaterialOS team](https://github.com/orgs/materialos/people) too:  :relaxed:

**Comment by ploctaux** [comment]
@HEXcube yup :)
@Foggalong could you add in the table how many apps materialos is covered please?

**Comment by deadbaed** [comment]
added MaterialOS to the list

**Comment by crutchcorn** [comment]
Yeah, @HEXcube, admittedly - I started MaterialOS with @danielhickman and Pinbadge is a @crutchcorn production with some assistance from a few others that ended up helping later on. To be fair, Pinbadge is the most likely to have a maintainer again soon (me; didn't mean to stop. Just got swamped) as it's simple to maintain. MaterialOS, while it could have a maintainer (depending on the team's thoughts, and I know I'd be willing for this one anyways), it's not a guarantee.

Oh, another fun tidbit of info about Pinbadge; the development for that icon pack is promised to be rampant when started again. Those numbers reflect like 3 months of work (if even).

Lastly, it's worth noting that @ikeydoherty is NOT on the Material team; meaning that we'd be in the cold if we ever wanted to have changes pushed upstream to improve the DE to match the specs.

**Comment by crutchcorn** [comment]
Oh, another fun tidbit of info about Pinbadge; the development for that icon pack is promised to be rampant when started again. Those numbers reflect like 3 months of work (if even)

**Comment by crutchcorn** [comment]
Lastly (sorry for spamming y'all), it's worth noting that Ikey (budgie dev, would tag but I'm stupid and on mobile so I forget his tag) is NOT on the Material team; meaning that we'd be in the cold if we ever wanted to have changes pushed upstream to improve the DE to match the specs

**Comment by RohanVilloth** [comment]
@crutchcorn I remember earlier versions of Solus having a Chrome OS like look an feel. Then it got a style of it's own with Arc and Moka theme.

While I'm a fan of Material Design :grin:, I'm not really sure if budgie-remix (or future Ubuntu Budgie) should follow a style entirely different from upstream Budgie. :confused: Selecting Material Design for icon theme alone (not for Widget theme) would be okay, I guess. :relaxed:

**Comment by uD4ra** [comment]
@HEXcube Yeah, I agree with you. I'm a fan of Material Design too.. :smile:  Nowadays Material design is trending everywhere, and It's also so nice. budgie-remix has to do own Style same as Solus did. :smile:

**Comment by ikeydoherty** [comment]
@HEXcube Budgie simply lacked theming capabilities back then. Everyone interpreted "transparent panel" as "ChromeOS". _shrug_.

Anyway, as for being "in the cold" - let's not speak on my behalf. If there are _general improvements_ to be made to Budgie, then yes, I'll accept them. If however on the other hand people want to push changes to turn it into a Playskool UI, then no, I'll reject them. Depends entirely on the _merit_ of the changes.

**Comment by RohanVilloth** [comment]
> Everyone interpreted "transparent panel" as "ChromeOS". shrug.

@ikeydoherty I wasn't just the transparent panel. Solus' icon theme (now discontinued Evopop) had a Material look too! :stuck_out_tongue_winking_eye: See:

![Old Solus with Evopop Icons](http://www.linuxinsider.com/article_images/2015/82295_990x555.jpg)

![Old Solus even more Materialish](http://i1-news.softpedia-static.com/images/news2/Let-s-Talk-Solus-the-Linux-Distribution-that-Wants-to-Change-the-Game-482307-5.jpg)

Looking back, they do look good! :heart_eyes: I wouldn't mind seeing the next budgie-remix come with a Material icon theme. :smiley:

**Comment by ikeydoherty** [comment]
@HEXcube which was _long after_ Budgie had had the same look for god knows how long. The look of Budgie didn't change to suit the GTK theme.

Fwiw - even though personally I don't like material design anymore (it's yet another hip fad that everyone is obsessed with and takes the lowest common denominator design approach of the convergence crowd that I can't stand .... )

... Budgie looks pretty friggin sweet with Adapta + Paper Icons. Disable the internal theming in Raven for Budgie and the latest Adapta has almost complete support now.

**Comment by RohanVilloth** [comment]
@ikeydoherty Did that already! :relaxed: Had tested Adapta on **budgie-remix** to help @tista500 solve a [compatibility issue with Tweak Tool and Budgie's Raven](https://github.com/tista500/Adapta/issues/40). See:

![Adapta with Budgie](https://cloud.githubusercontent.com/assets/3755396/14652461/0e1fd306-0692-11e6-9fec-e0f0a6289714.png)

![Adapta with Budgie Light](https://cloud.githubusercontent.com/assets/3755396/14652471/19188a82-0692-11e6-9470-35a24908445c.png)

I previously did a few screenshots of [Paper and Adapta on budgie-remix](https://github.com/budgie-remix/assets/tree/master/Screenshots/MaterialBudgie/), but those show mostly GNOME Apps. Now that Adapta implemented proper Budgie support and @snwh resumed Paper developement, I'll update the screenshots soon. :smile:

**Comment by snwh** [comment]
I'm going to unsub from this thread, if you land on Paper you know where to find me.

**Comment by RohanVilloth** [comment]
@snwh K sure! Will let u know if we choose Paper. :relaxed:

**Comment by fossfreedom** [comment]
covered by budgie-welcome - we can now switch to paper.
