### ISSUE TITLE
Window Focus

### ISSUE THREAD

**Issue by nsparks86** [UbuntuBudgie/budgie-desktop-environment#31]
I'm running 16.04, and I have Chrome set to a keyboard shortcut. When I launch a new browser window via keyboard shortcut, normally I can expect the focus to be on the address bar. However, even though the cursor is flashing on the address bar, when I begin typing, nothing shows up, and it actually is captured by the previous window I had open.

To duplicate, open something like mousepad/gedit, use a keyboard shortcut to open google-chrome (or guessing any application), and start typing. It will show up in the mousepad/gedit window.

At least that's the behavior I'm experiencing.

**Comment by fossfreedom** [comment]
hmm - does this Q&A help with focus issues?

http://askubuntu.com/questions/328843/focus-or-open-window-in-gnome-on-keyboard-shortcut

**Comment by nsparks86** [comment]
Tried it, doesn't seem to work. I'll search around. Guess the issue is deeper than budgie. I was on XFCE before this, and didn't have the problem. Seems this is Gnome based, probably a problem there.

**Comment by fossfreedom** [comment]
this one is older - should still work though
- http://unix.stackexchange.com/questions/13207/is-it-possible-to-raise-a-window-using-a-keyboard-shortcut-in-gnome3

**Comment by fossfreedom** [comment]
16.04 is no longer supported. Closing
