### ISSUE TITLE
Make Terminix the default terminal

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#33]
Terminix should be the default terminal - lets remove gnome-terminal from debian/control and substitute terminix

introduce an override to do the following:

    gsettings set org.gnome.desktop.default-applications.terminal exec gnome-terminal
    gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''

Overrides - dark theme

The VTE warning needs the recommendation ( https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue ) to add to the .bashrc to be done.  We can also then override the warning

overrides in /com/gexperts/Terminix

Note - the package needs to also remove the /etc/skel/.bashrc additions if budgie-desktop-environment is removed

**Comment by GrindamN** [comment]
I agree. Could be also a better option when using zsh and oh-my-zsh.

**Comment by uD4ra** [comment]
Yeah this is a great idea 😄 **Terminix** is just a fabulous Terminal
![virtualbox_zesty_19_11_2016_17_01_51](https://cloud.githubusercontent.com/assets/12265797/20455642/f4bcfd86-ae79-11e6-8977-0e5ca9371ad5.png)

**Comment by fu-sen** [comment]
Terminix's locale status:
https://github.com/gnunn1/terminix/tree/master/po
https://hosted.weblate.org/projects/terminix/

Because there was no Japanese there, I will translate immediately...

**Comment by fu-sen** [comment]
It is hardly translated. It will be in English display:
https://hosted.weblate.org/dictionaries/terminix/

**Comment by fossfreedom** [comment]
currently in the master branch

**Comment by fossfreedom** [comment]
ok - happy that this is incorporated in git correctly now.

**Comment by gnunn1** [comment]
Note that Terminix has been re-named to Tilix due to trademark infringement issues.

https://github.com/gnunn1/tilix

**Comment by fossfreedom** [comment]
@gnunn1 thanks - I know debian have a bug report open for this and tilix is currently in debian unstable.

I've similarly raised a report on launchpad for ubuntu but I suspect this will need to wait until 17.10 since ubuntu is in freeze pending 17.04 in 3 weeks.
