### ISSUE TITLE
change video player from totem to gnome-mpv

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#34]
Ubuntu's patching of totem means that full screen does not work correctly - the menu remains displayed.

Suggest gnome-mpv is a better fit.  Gnome-mplayer is far too complicated for most users I would suggest (willing to listen to counter arguments)

Need to ensure somehow that the default video application is "gnome-mpv" rather than just mpv.
Also remove the mpv menu item by blacklisting is in the same way as we did for imagemagick

**Comment by uD4ra** [comment]
@fossfreedom Why don't we use **VLC** player instead of this anything ?

**Comment by fossfreedom** [comment]
VLC is an excellent video player.  It though doesn't fit the GNOME style though very well - the default interface is a little odd looking for a budgie-desktop look and feel.

**Comment by uD4ra** [comment]
Yes But It'll not be a much problem, It's best matching with Arc theme.

**Comment by fossfreedom** [comment]
the default VLC interface out of the box is not very good.  It would be more work - but if we can find a good vlc-skin that fits the GNOME style ... and most importantly ... work out how to package the skin and make it the default then yeah VLC maybe worth looking at.

**Comment by uD4ra** [comment]
- VLC Default theme
  ![virtualbox_zesty_19_11_2016_09_43_41](https://cloud.githubusercontent.com/assets/12265797/20453489/a3d8ebfc-ae40-11e6-9e78-0a7d46ce4d12.png)
- VLC-Arc-Dark [Github](https://github.com/varlesh/VLC-Arc-Dark)
  ![virtualbox_zesty_19_11_2016_10_00_52](https://cloud.githubusercontent.com/assets/12265797/20453494/cf4fa0a0-ae40-11e6-8126-3139f931514b.png)
- VLC - MinimalX [DeviantArt](http://maverick07x.deviantart.com/art/VLC-MinimalX-385698882)
  ![virtualbox_zesty_19_11_2016_10_10_51](https://cloud.githubusercontent.com/assets/12265797/20453495/e795f4f2-ae40-11e6-96ad-20c6afb8eafa.png)

**Comment by fossfreedom** [comment]
gnome-mpv is now the default for 17.04
