### ISSUE TITLE
Change default cursor theme to breeze_snow

### ISSUE THREAD

**Issue by uD4ra** [UbuntuBudgie/budgie-desktop-environment#36]
![snow](https://cloud.githubusercontent.com/assets/12265797/20461694/0412b906-af1f-11e6-9b8f-5375274519fe.gif)

I think we should change default cursor theme to `breeze_snow` theme, It's available in Ubuntu universe repo `breeze` package.

![snow](https://cloud.githubusercontent.com/assets/12265797/20461672/50c94860-af1e-11e6-9339-e3644cdb1adc.png)

**Comment by fossfreedom** [comment]
I've added breeze-snow as a recommended package - so everyone can choose the cursor theme from raven from 17.04

As you say - the question is whether we change the default from DMZ-white to breeze-snow.

Think an across social media poll is required showing before and after screenshots ...

**Comment by uD4ra** [comment]
Ok will do another Poll for this issue, We'll see 😄
