### ISSUE TITLE
Sound applet icon display issue

### ISSUE THREAD

**Issue by dpjmv** [UbuntuBudgie/budgie-desktop-environment#38]
I am new on Budgie but i have noticed that issue when any sound is played.
![budgie sound bug](https://cloud.githubusercontent.com/assets/19637593/21243068/7dc49178-c317-11e6-910c-97884861429a.png)
Thanks for considering.

**Comment by fossfreedom** [comment]
Probably should be reported upstream....

What is the version of budgie desktop are you using?  What version of a budgie remix are you using? Is this only with vlc or with any media player?

**Comment by dpjmv** [comment]
The version is probably 10.2.9-0, i am not sure and i cannot check that now, and i tried with vlc, spotify and rhythmbox and the issue is always here.

**Comment by fossfreedom** [comment]
k - is it 16.04 or 16.10 you are using?

What icon-set are you using?

**Comment by dpjmv** [comment]
I am using ubuntu 16.04 with arc gtk darker theme and papirus icons
I will try without the pack as soon as i can

Le samedi 17 décembre 2016, David Mohammed <notifications@github.com> a
écrit :

**Comment by fossfreedom** [comment]
thanks - please try with adwaita iconset and moka-icon set.

We need to understand if this is specifically a papirus icon set issue or a more general issue.

**Comment by dpjmv** [comment]
same problem with both

**Comment by dpjmv** [comment]
I also have the same issue with another computer using ubuntu 16.10

**Comment by fossfreedom** [comment]
ok - there is definitely a bug here - the built in theme option works just fine.  It is because you have disabled the built-in theme.  I'll discuss upstream for you.

**Comment by dpjmv** [comment]
Ok thanks

**Comment by fossfreedom** [comment]
This issue was moved to UbuntuBudgie/budgie-desktop#8
