### ISSUE TITLE
Display orientation

### ISSUE THREAD

**Issue by cosimochellini** [UbuntuBudgie/budgie-desktop-environment#39]
The screen orientation is reversed, if I tilt the pc back normal.
Its pretty weird, i know

**Comment by fossfreedom** [comment]
yes - that is standard behaviour - it helps with people with monitors that switch orientation.

If you want to fix the position then this Q&A will help: https://answers.launchpad.net/budgie-remix/+question/293362

**Comment by cosimochellini** [comment]
thanks so much for the help
