### ISSUE TITLE
Menu not updating

### ISSUE THREAD

**Issue by jasonehines** [UbuntuBudgie/budgie-desktop-environment#43]
If I install an app with snap or apt it does not show up in the budgie menu.

My workaround is to open the panel settings and remove and add back the budgie menu.

**Comment by fossfreedom** [comment]
Hi,
  we have some testing packages that should hopefully resolve this issue.

Please give these a go and let us know the results.  We are particularly interested if you see any panel crashes or whole session crashes - hopefully you won't.

    sudo add-apt-repository ppa:budgie-remix/proposed 
    sudo apt-get update

To undo:

    sudo ppa-purge ppa:budgie-remix/proposed

thanks

**Comment by jasonehines** [comment]
Awesome! That took care of the menu issue for snap and apt installs.

**Comment by fossfreedom** [comment]
thanks for testing.  Much appreciated.  I have sync'd the proposed packages now - you can now update and ppa-purge the proposed repo.
