### ISSUE TITLE
Two icons for Files

### ISSUE THREAD

**Issue by jasonehines** [UbuntuBudgie/budgie-desktop-environment#44]
When I launch Files from the menu I get two icons for Files on Planks doc. One doesn't have the blue indicator under the other does. After about 10 seconds the first one, without the indicator, goes away. It seems to just be a UI issue.

**Comment by fossfreedom** [comment]
16.04 or 16.10?

Have you got desktop icons switched on or off in Raven?

**Comment by jasonehines** [comment]
desktop items is on

**Comment by fossfreedom** [comment]
Duplicate menu items fixed in 19.04
