### ISSUE TITLE
Screen 90°

### ISSUE THREAD

**Issue by juanminino** [UbuntuBudgie/budgie-desktop-environment#58]
Ubuntu Budgie 17.04 with kxstudio (included lowlatency kernel)
notebook hp pavilion g4
sometimes screen rotates 90° to the right 
(I restart in that cases)
Sorry for my poor english
------
A veces, repentinamente la pantalla rota 90° a la derecha . Cuando eso pasa yo reinicio la notebook.

Gracias!

**Comment by fossfreedom** [comment]
try this in a terminal:

    gsettings set org.gnome.settings-daemon.plugins.orientation active false

**Comment by juanminino** [comment]
Thank you!
