### ISSUE TITLE
Change GTK Theme

### ISSUE THREAD

**Issue by Foggalong** [UbuntuBudgie/budgie-desktop-environment#6]
Discussion about GTK themes transferred from #3

> _@spottech_: Move from Arc to Papirus GTK. It's mine and it's great lol

![capture du 2016-04-20 17-22-04](https://cloud.githubusercontent.com/assets/13060777/14680139/75580b8a-071c-11e6-970d-14d37c71524f.png)

> _@HEXcube_: For 16.04.x we're staying on Moka icons and Arc GTK theme to follow the style of Solus 1.x. Do you mean [this one](http://www.noobslab.com/2015/10/papirus-icons-for-unity-papirus-theme.html) and [this](https://github.com/varlesh/papirus-suite)? :confused: I confused it with [Papyros](https://papyros.io) at first, lol! :laughing:
> 
> _@spottech_: Yes this, it's great :D

**Comment by RohanVilloth** [comment]
These are my suggestions:
- **Adapta**:  Material Design inspired. Recently implemented full support for Budgie.
- **Paper** from Sam Hewitt (@snwh), the creator of Moka icon theme. Like Adapta, it's Material Design inspired too. :relaxed:
- **Numix**: Flat and modern. It's so popular that it needs no further description. :smiley:
- **Vertex**: From @horst3180 , the creator of _Arc_ theme we're using in budgie-remix 16.04. Vertex is already bundled with budgie-remix as a choice. It's got first class Budgie support.
- Or continue with **Arc**, coz it's really good. And as long as it's Solus official theme, we don't have to worry about any breakages :grin:

**Comment by spottech** [comment]
Arc it's the best choise

**Comment by fossfreedom** [comment]
closed - we now cover this via budgie-welcome and the ability to switch to adapta
