### ISSUE TITLE
Icons display artifact when dragged 

### ISSUE THREAD

**Issue by GrindamN** [UbuntuBudgie/budgie-desktop-environment#61]
When dragged, icons will copy part of the background, thus displaying weird artifact around them. Budgie desktop 10.3.1. It could be due to MESA or Kernel. I'll try to investigate and return more information.

**Comment by GrindamN** [comment]
Confirmed that the problem is caused due to global-menu applet being installed.

**Comment by fossfreedom** [comment]
Issue should be reported upstream on the app menu project
