### ISSUE TITLE
Additional IconTheme and new default one

### ISSUE THREAD

**Issue by GrindamN** [UbuntuBudgie/budgie-desktop-environment#62]
We should explore adding additional IconTheme alongside current ones. It would be nice to go for something between material style and icons that Solus OS uses at the moment.

**Comment by ckrzen** [comment]
+1 for "Paper"(icons,gtk,cursors):

https://github.com/snwh/paper-icon-theme

https://github.com/snwh/paper-gtk-theme

**Comment by fossfreedom** [comment]
@ckrzen paper-gtk-theme appears to be unmaintained now, so not really a good long term solution.

**Comment by ckrzen** [comment]
Bummer. I like the fact that 'Paper' didn't change the default look of
"Chrome" browser icons while still giving a modern(Material) look to GNOME
stuff.

**Comment by ckrzen** [comment]
OK ... after having another look at "Pocillo" during a new install of 17.10, I have to admit --- I like it _better_ than "Paper".

This article may be of interest:  http://www.linuxandubuntu.com/home/10-best-icon-themes-for-linux

and

https://github.com/anmoljagetia/Flatabulous

**Comment by fossfreedom** [comment]
Theme makeovers in welcome covers this
