### ISSUE TITLE
Create template files for GNOME Files

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-desktop-environment#63]
See this AskUbuntu answer for _"How to create a new empty file/template file in Ubuntu?"_: [Link to Answer](https://askubuntu.com/questions/837227/how-to-create-a-new-empty-file-template-file-in-ubuntu-16-10-desktop#837521)

Suggest should add these to `/etc/skel` so that templates appear in the `New Document` right click menu in GNOME Files

**Comment by RohanVilloth** [comment]
This is what I currently use:

[Templates.tar.gz](https://github.com/UbuntuBudgie/budgie-desktop-environment/files/1008692/Templates.tar.gz)

![new document](https://cloud.githubusercontent.com/assets/3755396/26169324/d176523c-3b5a-11e7-8fcd-b9000772f5aa.png)

**Comment by RohanVilloth** [comment]
I think we should package the Templates in 2 sets:

- One for regular users with common filetypes like Empty File, Text File, Presentation, Office Document, Spreadsheet, PNG Image, etc. Let's try to keep it in a single level menu. This one needs to be simple enough to be a default install package.

- The second one for more advanced users, cascading levels of Web Documents (HTML, CSS, JS, Markdown), Scripts (Python, Lua, Perl, etc), Images (PNG, JPEG, GIMP XCF, SVG, etc) and more...

The second one isn't really high priority though. Most regular users'd need just basic filetypes.

**Comment by fossfreedom** [comment]
I just need a definitive templates structure please. We can't package two lots of templates

**Comment by fossfreedom** [comment]
17.10 has template files.  Whether they are the right ones is a different matter.
