### ISSUE TITLE
Enable hibernation by default in Ubuntu Budgie

### ISSUE THREAD

**Issue by sidahmed-malaoui** [UbuntuBudgie/budgie-desktop-environment#64]
To activate hibernation on ubuntu-budgie, I had to go through some pretty complicated and long procedure that you can find right  [here](https://askubuntu.com/questions/913517/cannot-hibernate-ubuntu-budgie-17-04?noredirect=1#comment1438642_913517) .

So can you please enable hibernation by default on Ubuntu Budgie.

**Comment by fossfreedom** [comment]
hibernation is one of those hit and miss aspects of linux.  

So no - hibernation will not be made a default option.

However I am more than happy to accommodate an option via budgie-welcome to enable hibernate during the first desktop setup.

So if you - or anyone can come up with a bash script that automates the Ask Ubuntu answer I will insert that into budgie-welcome.

**Comment by fossfreedom** [comment]
decided against this.  Hibernation needs to be managed outside of the distro since the broken nature of hibernation for most people would cause too much support issues
