### ISSUE TITLE
BUG of lightcontrol with thinkpad t430 with only nvidia card enabled

### ISSUE THREAD

**Issue by 243750496** [UbuntuBudgie/budgie-desktop-environment#67]
![1](https://user-images.githubusercontent.com/6311930/27633821-5b7e6c6e-5c33-11e7-9578-a02454118378.png)

when i press fn+F10 (set high value) it wil auto maticly go min value,and doing nothing (if the value is min the screen should be black but nothing happened)

BTW:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_osi=Linux acpi_backlight=vendor"`
**witch is edited of the /etc/default/grub**
```
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVS 5400M"
    Option         "RegistryDwords"  "EnableBrightnessControl=1"
EndSection
```
**edited the file /etc/X11/xorg.conf**

**Comment by fossfreedom** [comment]
This looks like a bug with nvidia graphics.  I don't see why this is a budgie-desktop issue.

**Comment by 243750496** [comment]
I tried all the version witch both open-source or proprietary none working  but it working well with  the previous driver (Witch also tested but not working on Ubuntu  budgie ) under Ubuntu  16.10 so i thought it  must  be  a bug

**Comment by fossfreedom** [comment]
16.10 is a different kernel.  You can install gnome-shell and login to that.  If it works then yeah its a budgie-desktop issue.  Budgie desktop issues should be reported upstream here https://github.com/budgie-desktop/budgie-desktop
