### ISSUE TITLE
App-indicator icons increases panel size

### ISSUE THREAD

**Issue by ruffson** [UbuntuBudgie/budgie-desktop-environment#69]
I already posted this in the budgie-desktop repo but was told, that this is an ubuntubudgie issue, so here again.

**Operating System**: Ubuntu 16.04.3
**Budgie version**: Budgie 10.4

**The issue encountered**

 I just updated my budgie desktop under ubuntu to 10.4. And noticed that my top panel is not as small anymore as before. Rather, the OS icons scaled with the panel size, but the panel itself is rather fat.

It seems that some of the third-party icons are causing the panel to be larger, which was not the case before. I would expect that resizing the panel would either resize all the icons (they are rendered in some way budgie knows of) in the panel. Or reverting back to the original state where the panel would be made smaller and with that the margin around the third-party icons. 

This way is wasting a lot of screen estate. Here is a screenshot:
![panel size](https://user-images.githubusercontent.com/1185812/29997421-8c92bdc4-8fc7-11e7-8955-cc974f683ea0.png)

Is there anything I can do for now to get this fixed?

Update of two new observations:

- When starting something like steam which has a larger icon than others, the panel just increases to that ridiculous size.
- When you drag windows to the top they go through the extra panel-space until they are stopped by the set panel size. This panel management is seriously screwed up.

Here another screenshot: 
![panel2](https://user-images.githubusercontent.com/1185812/29997537-b6eea634-8fca-11e7-8836-617f2c300513.png)

**Comment by fossfreedom** [comment]
The key icon in that screenshot is steam. Close it and you will be able to shrink the panel.

The steam icon in /usr/share/icons needs to be 22px in size. The icon set you are using looks to be using a 48px or larger. Shrinking the steam icon size fixes this

**Comment by ruffson** [comment]
Yes, in the second example its steam and in the first example its the app-indicator. 

The problem is that before I updated, the panel size would stay true to whatever I set it to be and would just cut off icons if they are to big. Not it seems that icon renderings have a higher priority and mess up everything.


Update:

Even without steam, since 10.4 the panel is miuch bigger than I set it to be and obstructs windows when dragged into it:

![messup](https://user-images.githubusercontent.com/1185812/30005183-8aebe9ee-9091-11e7-83ab-5538f78e5164.png)

**Comment by ruffson** [comment]
@fossfreedom Or can you tell me what updates I have to revert to get back to a working OS without these bugs?

**Comment by fossfreedom** [comment]
@ruffson remove the appindicator is the simplest solution.

**Comment by ruffson** [comment]
Wow

**Comment by fossfreedom** [comment]
linking this issue to here - needs a C based code patch - https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/3

help always welcome.

**Comment by fossfreedom** [comment]
@ruffson please can you urgently test a possible fix for your issue please ? 

instructions here - thanks https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/3

**Comment by ruffson** [comment]
@fossfreedom I'm sorry, I abandoned Budgie because of this.
