### ISSUE TITLE
Change default font

### ISSUE THREAD

**Issue by RohanVilloth** [UbuntuBudgie/budgie-desktop-environment#7]
We need to decide on a new font, not just for the desktop, but for all branding, wordmarks and media. It'll help increase consistency and brand identity.

![budgie-remix-logotype](https://cloud.githubusercontent.com/assets/3755396/14862565/a3c25a44-0ccf-11e6-86e9-52a312a0868c.png)

Currently budgie-remix uses _Ubuntu_ fonts on the desktop and for most branding. While it's a good font, I don't think using it on all _budgie-remix_ brand materials is a good idea. :confused:

**Comment by uD4ra** [comment]
**What about this Fonts ?** check this out.. 
- https://github.com/theleagueof/raleway
- https://www.google.com/fonts
- https://fontlibrary.org/en/font/glacial-indifference
- https://www.fontsquirrel.com/fonts/corbert

**Comment by fossfreedom** [comment]
suggestion from Alexander Browne via G+ - Source Sans Pro from Adobe  - according to wikipedia debian does approve of the license its released under.

For any suggestion here we need to visually see how these fonts look i.e. take HEXcubes example above and change the font for the "budgie-remix"

**Comment by apolitech** [comment]
I realy like https://github.com/theleagueof/raleway!

**Comment by uD4ra** [comment]
Here I have created **budgie-remix Logo** using some different Fonts...
Just take a look at that, and let me know about your opinions..

![budgie-remix-fonts](https://cloud.githubusercontent.com/assets/12265797/15348888/66bab086-1cdf-11e6-96d5-62bda859a837.png)

**Comment by apolitech** [comment]
Comfortaa+1

**Comment by RohanVilloth** [comment]
The font shouldn't be too fancy, coz it's not just the wordmark we're using the font for. The whole desktop, apps and pretty much all the text elements in the distro'll use this new font. So, we've to select something that'd be comfortable to use for daily work. :relaxed:

**Comment by fossfreedom** [comment]
from the above ubuntu (light) fonts and source sans pro are the obvious choices.  Havent tried to install the source sans pro fonts in budgie-remix to see how they are usuable on a day-to-day basis.

**Comment by uD4ra** [comment]
So why should we use the same font for the Wordmark and Desktop ?
It' should not be like that, because as  remember Ubuntu Gnome or elementary os using Droid Sans for their Desktop.But Not for the Wordmark. Wordmark is a Logo, But not Iconic that's it.

**Comment by elcste** [comment]
I made the suggestion of of Adobe Source Sans Pro (and Source Code Pro for monospace). (I was on vacation and using my phone, and I think I deleted the post accidentally, but David saw it.) These fonts are designed for user interfaces, and look really good on screen. It's the first thing I personally install on any new Linux install.

They are free software, developed on Github. You can download the fonts via the releases tab on Github:

https://github.com/adobe-fonts/source-sans-pro
https://github.com/adobe-fonts/source-code-pro

They are not in Debian/Ubuntu, but if I remember right it was a license issue early on that was changed. (They are in Fedora FWIW.)

Another advantage is that they support a large character set, including more "obscure" accents, Greek, and Cyrillic, so people who aren't using English still get to use the font! The Chinese/Japanese/Korean font was developed along with Google and is the same (or nearly the same) as Noto Sans CJK, and the other non-Latin Noto fonts are a good match, so South and Southeast Asian languages would look good too.

**Comment by elcste** [comment]
I also agree that the wordmark font does _not_ need to be the same as the desktop/UI font. The logo might want to be more visually interesting, while the UI font should be functional. That said, I don't think they _have_ to be different.

One idea is to use two different fonts, one for each word. Another idea is to use the Ubuntu font to show the Ubuntu heritage. Combining those ideas, here's one suggestion with "Budgie" in Source Sans Pro bold and Remix in Ubuntu light:

![budgie remix ssp u](https://cloud.githubusercontent.com/assets/915687/15799682/f51080de-2a29-11e6-9e4b-b4cf0229bcb3.png)

I think titlecase looks more polished, and that the hyphen isn't needed in a standalone form, but the fonts work either way. Here's a version following those conventions: 

![budgie remix ssp u lc hyphen](https://cloud.githubusercontent.com/assets/915687/15799709/6f2a7b72-2a2a-11e6-9a57-27c379269733.png)

**Comment by fossfreedom** [comment]
@abrowne I'm not aware of a .deb package for these fonts.  Have you found a .deb to install these easily?  If not - we'll need package these correctly.

**Comment by elcste** [comment]
No, unfortunately not. I've been downloading the Github archives and
manually installing the fonts. I had thought about attempting a package,
but I'm a linux noob. I'm interesting in helping if it would be useful.

On Sat, Jun 4, 2016 at 9:43 AM, David Mohammed notifications@github.com
wrote:

> @abrowne https://github.com/abrowne I'm not aware of a .deb package for
> these fonts. Have you found a .deb to install these easily? If not - we'll
> need package these correctly.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/budgie-remix/budgie-desktop-environment/issues/7#issuecomment-223759287,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA3457eWeNOU0VJfDNFCaAVHpAjComNSks5qIY8GgaJpZM4IRLjY
> .

## 

Alexander Browne

**Comment by RohanVilloth** [comment]
From @abrowne's description, _Source Sans Pro_ looks interesting.

> One idea is to use two different fonts, one for each word. Another idea is to use the Ubuntu font to show the Ubuntu heritage.

That's how **Ubuntu GNOME** does it! :smiley: See:

![Ubuntu GNOME Wordmark](https://wiki.ubuntu.com/UbuntuGNOME/Artwork/Graphics?action=AttachFile&do=get&target=logo_medium.png)

> I think titlecase looks more polished, and that the hyphen isn't needed in a standalone form

The reason it's styled **budgie-remix** in lowercase is to indicate the unofficial flavor status. Once it goes official, budgie-remix'll get rebranded to **Ubuntu Budgie**. Then we can have Title Case! :relaxed:

**Comment by elcste** [comment]
@HEXcube 

> The reason it's styled budgie-remix in lowercase is to indicate the unofficial flavor status. Once it goes official, budgie-remix'll get rebranded to Ubuntu Budgie. Then we can have Title Case! 

Aha, that makes sense ;-)

**Comment by niyasc** [comment]
Anyone for _**Cantarell**_? Default font used by GNOME.

**Comment by uD4ra** [comment]
So check this out :smile: 
![new wordmark ideas](https://cloud.githubusercontent.com/assets/12265797/15849779/d67208c6-2c9c-11e6-8268-5dc1799bab95.png)

**Comment by fossfreedom** [comment]
source sans pro light + Normal + blue is absolutely gorgeous !

**Comment by RohanVilloth** [comment]
Solus and hence upstream Budgie desktop has **Clear Sans** as the default font. It's an open source font designed by Intel and made available under Apache 2.0 license. See the [font's homepage](https://01.org/clear-SANS). However, it's not on Debian repos yet. :worried:

For the monospace font, Solus uses [Hack](https://sourcefoundry.org/hack/). See the [announcement on G+](https://plus.google.com/+Solus-Project/posts/4KXwDDdQuuW). This one is available on Debian as [fonts-hack-ttf](https://packages.debian.org/sid/fonts/fonts-hack-ttf) package. :relaxed:

**Comment by RohanVilloth** [comment]
I made a wordmark with **Ubuntu** and **Clear Sans** fonts. :smiley: See:

![ubuntu-budgie-wordmark-preview](https://cloud.githubusercontent.com/assets/3755396/16177105/930fc380-3641-11e6-8be3-318c4b710a44.png)

I followed the 2 color scheme of [Ubuntu MATE wordmark](https://dribbble.com/shots/2505097-Ubuntu-Mate-Logo), which is in-turn is derived from [Ubuntu GNOME wordmark](https://www.behance.net/gallery/25233455/The-Ubuntu-GNOME-Brand).  

**Ubuntu GNOME wordmark**:
![Ubuntu GNOME Wordmark](https://wiki.ubuntu.com/UbuntuGNOME/Artwork/Graphics?action=AttachFile&do=get&target=logo_medium.png)  

**Ubuntu MATE wordmark**:
![ubuntu-mate-wordmark](https://cloud.githubusercontent.com/assets/3755396/16177150/b9b82a1c-3642-11e6-968d-d73f44c9dc42.png)  

However, the budgie-gray color from our palette (#404552) isn't that distinguishable from black like that of Ubuntu MATE. And note that I didn't make the _Budgie_ wordmark bold like GNOME and MATE. That's coz _Budgie_ isn't an abbreviation like the others and I've not seen _Budgie_ stylized as bold by upstream _Solus_. But, the resulting _Budgie_ wordmark doesn't really stand out in the final output. :worried:  

Anyway, I pushed the source svg files (`ubuntu-budgie-wordmark-source.svg`, `ubuntu-budgie-wordmark.svg`, `ubuntu-budgie-wordmark-light.svg` and `ubuntu-budgie-wordmark-preview.svg`) to our [assets repo](https://github.com/budgie-remix/assets/tree/master/Logos/). When we finalize an official font later, we can rebase the wordmarks to that font. :relaxed:  

Related resources:
[Ubuntu GNOME's brand assets repo](https://github.com/UbuntuGNOMEMarketing/ubuntu-gnome-artwork/tree/master/brand/)
[Ubuntu MATE's artwork repo](https://bazaar.launchpad.net/~ubuntu-mate-dev/ubuntu-mate/artwork/files)

**Comment by RohanVilloth** [comment]
Well, I updated the wordmark and went for bold Budgie! :grin: The bold version by @Udara-U3 was already in use on our [website](https://ubuntubudgie.org) and I think it looks better. So, I just decided to update it officially. See commit: https://github.com/UbuntuBudgie/assets/commit/ef0eb3bd7f4b6f93ffee7665531a68c15b8efcb2

![ubuntu-budgie-wordmark-preview](https://cloud.githubusercontent.com/assets/3755396/25070520/703fbc6a-22be-11e7-9022-dab84099a7de.png)

**Comment by denji** [comment]
Ubuntu Budgie (17.04) terrible ubuntu-based font...
Will need to transfer all changes manually from Solus for a better experience.

Solus Fonts
-------------
![solus-project-font](https://cloud.githubusercontent.com/assets/3759759/25310229/764da3c2-27e8-11e7-9aaa-c83e469c5203.png)

**Comment by fossfreedom** [comment]
OBE - 19.04 using noto-sans
