### ISSUE TITLE
Failed to take a screenshot (Ubuntu Budgie 17.10)

### ISSUE THREAD

**Issue by CeCallejas** [UbuntuBudgie/budgie-desktop-environment#70]
When taking a screenshot is also captured the screenshot applications window

![photo_2017-10-10_09-54-09](https://user-images.githubusercontent.com/13605392/31396592-06603f40-ada1-11e7-9209-e5e73646a5e9.jpg)

**Comment by Jacob-Vlijm** [comment]
Normally, the screenshot window should close after pressing "Take screenshot". Then after the shot is taken, the save- dialogue window should appear. Does the second window appear? What happens to the first window if so?

**Comment by CeCallejas** [comment]
The window is hidden, but when taking the screenshot this is captured. Both the window before the capture and after the capture seems to work fine. My laptop uses an Intel 3000 Graphics, 8GB RAM and an Intel i5

**Comment by CeCallejas** [comment]
Error, the problem only occurs in a virtual machine of VirtualBox. I will close this problem.
