### ISSUE TITLE
Follow branding guidelines suggested by upstream Budgie

### ISSUE THREAD

**Issue by RohanVilloth** [UbuntuBudgie/budgie-desktop-environment#8]
Re-implement our branding and configuration overrides for Budgie desktop based on the upstream guidelines. See the repo holding [Budgie remix branding overrides](https://github.com/solus-project/budgie-desktop-branding).

Another upstream commit enabled changing panel layout by supplying `$(datadir)/budgie-desktop/panel.ini`. We should make use of this change too! :smile:

By choosing to follow upstream supported methods for overriding, we can reduce the number of patches and so maintenance'll become easier. :relaxed:

**Comment by fossfreedom** [comment]
just noticed - we implemented this a long time ago!
