### ISSUE TITLE
Quick app and keyboard layout switcher

### ISSUE THREAD

**Issue by Lisio** [UbuntuBudgie/budgie-desktop-environment#80]
This is a feature request. Moved to 17.10 Budgie from 16.04 Unity and productivity decreased drastically. I have to switch between apps and between the windows of the same app rather often and in Unity it looks like these: for example, sublime text is attached to dash as 3rd icon.
1. Press Super+3 from any place - switches to sublime.
2. Press Super+3 when in sublime - shows overview of all opened windows of sublime
3. Hold Super and press 3 - switches between sublime windows.
So in Unity I had 5 mostly used apps and could switch between them using Super+{1-5} extremely fast. This is a killer feature for me and I miss it very much.

The second missing feature is the ability to change layout using Control+Shift. I can set it with
```
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Control>Shift_L']"
```
but it starts to change layout for Control+Shift+T and another similar combinations. This is because the event is fired immediately when these keys are pressed, and not when the keys are released.

If I miss something, please let me know. The real problem is that GShell works not like Unity and when I press Super+3 every single time it asks which sublime window to open (and it has the same problem with layout switch, I think it's connected with IBus or something like that).

**Comment by Jacob-Vlijm** [comment]
Feature requests like this should be posted upstream with Budgie desktop https://github.com/budgie-desktop/budgie-desktop, but keep in mind that Unity is not Budgie and vice versa. Changing DE always means you will have to change some habbits.
