### ISSUE TITLE
Allow different sources for each window doesn't work

### ISSUE THREAD

**Issue by Lisio** [UbuntuBudgie/budgie-desktop-environment#81]
Ubuntu 17.10 Budgie. The option "Allow different sources for each window" is ignored and source changes for all apps and windows.

**Comment by Jacob-Vlijm** [comment]
Please use the Keyboard Autoswitch Applet. Which automatically remembers which layout you set for which application. Activate backports from Budgie Welcome, update and install from Welcome.

**Comment by Lisio** [comment]
I don't need to set default layout per application forever. It should be EN by default for every app, but when I switch layout to RU it should be changed only for current window and current session, until the window is closed or layout changed back to EN again. This is the idea that stands behind the "Allow different sources for each window" option.

**Comment by fossfreedom** [comment]
This isn't something we can resolve ourselves - its a budgie-desktop issue upstream
