### ISSUE TITLE
Replace the built in "show-desktop" by the one that comes with the hotcorners applet

### ISSUE THREAD

**Issue by Jacob-Vlijm** [UbuntuBudgie/budgie-desktop-environment#82]
The built-in option to show desktop (set in `/org/gnome/desktop/wm/keybindings/show-desktop`) is quite harsh. There is no animation whatsoever, and the currently active window is not respected. The hotcorners- applet includes a script to toggle desktop, `/usr/lib/budgie-desktop/plugins/budgie-hcorners/showdesktop`, which works more smoothly and remembers the previously active window on show.

**Comment by fossfreedom** [comment]
fixed as per commit in issue #11
