### ISSUE TITLE
Arc darker theme does not play well with symbolic icons of wsoverview

### ISSUE THREAD

**Issue by Jacob-Vlijm** [UbuntuBudgie/budgie-desktop-environment#90]
The arc them on 18.04 does not set the color correctly on the icons of wsoverview; all icons appear grey now. Not sure if this is the right place though to file this.

![screenshot from 2018-03-31 23 31 05](https://user-images.githubusercontent.com/8932980/38167758-a810ec82-353b-11e8-8ef3-91bf07244e7a.png)

(nearly visible, next to the hotcorners icon)

**Comment by fossfreedom** [comment]
This issue was moved to NicoHood/arc-theme#64
