### ISSUE TITLE
Per monitor display scaling

### ISSUE THREAD

**Issue by jack828** [UbuntuBudgie/budgie-desktop-environment#91]
Hello!

I'm trying to use the `Displays` settings to set my primary (2560x1440) laptop display to have 200% scale, with an external display (1920x1200) to have 100% scale.

Currently, it allows me to change any settings I like, showing the `Apply` button to save - but when I change my external monitor's scaling to 100%, this button disappears!

Please let me know what information you need from me.
![image](https://user-images.githubusercontent.com/6363719/38932510-5a51d7b4-430e-11e8-9694-3247ce3a47f9.png)

**Comment by fossfreedom** [comment]
@jack828 my understanding is that there is a certain threshold introduced by GNOME for 3.28  where they hide the scaling button if the resolution is thought to not be HiDPI.  So gnome-control-center via the mutter window manager thinks its no longer in HiDPI mode and hides the button when you've fiddled with the scaling.  Maybe its getting a little confused on which display it is the primary.

Suggest raise a bug report on launchpad and report this observation.

    ubuntu-bug gnome-control-center

**Comment by jack828** [comment]
@fossfreedom Thank you! I'll head over there.

**EDIT:** Launchpad bug report:
https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1765044

**Comment by fossfreedom** [comment]
Not something we can deal with as a project - upstream GNOME issue
