### ISSUE TITLE
Settings > Devices > Keyboard > Navigation does not include "Move to workspace {left | right}"

### ISSUE THREAD

**Issue by craysiii** [UbuntuBudgie/budgie-desktop-environment#97]
Trying to configure my hotkeys on a new install, and realized that the only options were {up | down}. 

In other tutorials I see that these options are available, were they removed? Or did I bork my system?

**Comment by fossfreedom** [comment]
Ctrl alt left and right arrows should be custom shortcuts in the full UB install. They control left and right workspaces and also dynamic workspaces

**Comment by craysiii** [comment]
Wow, thanks. Didn't see that, probably didn't look hard enough.
